mysite/example/urls.py
from django.urls import path
from . import views

app_name = 'example'
urlpatterns =[
    path('',views.show, name="show"),
    path('<int:id>/', views.product_detail, name="product_detail"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path



urlpatterns = [
    path('ex/', include('example.urls')),
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
    
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
   # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/example/models.py
from django.db import models

# Create your models here.
class Product_catogories(models.Model):
    catogory_name = models.CharField(max_length=200) 

    def __str__(self):
        return self.catogory_name

class Products(models.Model):
    catogory = models.ForeignKey(Product_catogories, related_name="products", on_delete=models.CASCADE)
    product_name = models.CharField(max_length=200)
    product_cost = models.IntegerField()

    def __str__(self):
        return self.product_name

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question,related_name='choices', on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/example/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Products
# Create your views here.

def show(request):
    data = {'Products': Products.objects.all().order_by('-product_cost')}
    return render(request,'example/products.html',data )

def product_detail(request):
    sp = Products.objects.get(pk=id)
    return render(request, 'example/product_detail.html', {'product':sp})

mysite/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Choice, Question


# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'polls/index.html', context)

def index(request):
    list_question = Question.objects.all()
    # list_choice = Choice.objects.all()

    for question in list_question:
        print(question)
        Choice.objects.filter(question=question.id)

    context = {'qs': list_question}
    # context = {'ch': list_choice}  
    return render(request,"polls/index.html",context )

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    choices = Choice.objects.filter(question=question_id)
    

    return render(request, 'polls/detail.html', {'question': question, 'choices': choices})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})
    
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    
    try:
        selected_choice = question.Choices.get(pk=request.POST['choice'])

    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/example/templates/example/product_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detail</title>
</head>
<body>
    <h2>product detail</h2>
    <ul>
        {% for x in product %}
            <li>{{ x.catogory }}</li>
            <li>{{ x.product_name }}</li>
            <li>{{ x.product_cost }}</li>
        {% endfor %}
    </ul>
</body>
</html>

mysite/example/templates/example/products.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Products</title>
</head>
<body>
    <h2>Products:</h2>
    <ul>
    {% for x in Products %}
     
        <li><a href="{% url 'example:product_detail' x.id %}">{{ x.product_name }}</a></li>
        <!-- <li>{{ x.product_name }}</li> -->
    {% endfor %}
    </ul>
</body>
</html>

mysite/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in choices %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>
    

mysite/polls/templates/polls/index.html
<!-- {% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %} -->

 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Question</title>
</head>
<body>
    
    <h2>Question:</h2>
    <ul>
      <!-- {% for question in qs %}
        <li>{{ question.question_text }}</li>
        
      {% endfor %}  -->

      {% for question in qs %}
        <li>{{ question.question_text }}</li>
        <!-- <li>{{ question.question_related.all }}</li> -->
        {% for x in question.question_related.all %}
        <p>{{ x.choice_text }}</p>
        {% endfor %}
      {% endfor %}
    </ul>
</body>
</html>

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in choices %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>